# Generated by Django 4.0.6 on 2022-09-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='category_products',
        ),
    ]
